export interface dashboardPorpesInterface{
    dashboard:boolean,
    employee?:boolean,
    head?:boolean,
    AllSales?:boolean,
    leads?:boolean,
    inbox?:boolean,
    call?:boolean,
    toDo?:boolean,
    messenger:boolean,
    profileInfo:boolean,
    setProfileInfo:React.Dispatch<React.SetStateAction<boolean>>,
    setDashboard:React.Dispatch<React.SetStateAction<boolean>>,
    setEmployee:React.Dispatch<React.SetStateAction<boolean>>,
    setHead:React.Dispatch<React.SetStateAction<boolean>>,
    setMessenger:React.Dispatch<React.SetStateAction<boolean>>,
    setAllSales:React.Dispatch<React.SetStateAction<boolean>>,
}